[package]
name = "sync-locale"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/wishyoudie/localizer"

[dependencies]
colored = "3.0.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
